apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: demoacraz204.azurecr.io/sample-springboot-image2:latest
